# Generated by Django 4.2.3 on 2023-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0002_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
